<a href="https://colab.research.google.com/github/trupti2021/FirstGIT/blob/main/BronzeLoanClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [8]:
df=pd.read_csv("/content/drive/MyDrive/AutogluonDrop/loan_dataset.csv")

In [9]:
df

,Age,Annual_Income_Lakhs,Credit_Score,Loan_Amount_Lakhs,Loan_Term_Years,Employee_Type,Loan_Approved
0,25,4.5,650,5,5,Salaried,Yes
1,30,6.2,720,8,10,Salaried,Yes
2,28,3.8,600,4,5,Self Employed,No
3,35,10.5,780,12,15,Salaried,Yes
4,40,12.0,800,15,20,Salaried,Yes
...,...,...,...,...,...,...,...
95,54,10.7,745,10,14,Self Employed,Yes
96,59,9.2,725,9,16,Salaried,Yes
97,38,5.2,595,3,9,Self Employed,No
98,41,9.7,755,8,14,Salaried,Yes
99,36,5.7,625,4,10,Salaried,No

In [13]:
df['Annual_Income_Lakhs']=df['Annual_Income_Lakhs'].astype(str)

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Employee_Type']=le.fit_transform(df['Employee_Type'])
df['Loan_Approved']=le.fit_transform(df['Loan_Approved'])

In [20]:
df

,Age,Annual_Income_Lakhs,Credit_Score,Loan_Amount_Lakhs,Loan_Term_Years,Employee_Type,Loan_Approved
0,25,4.5,650,5,5,0,1
1,30,6.2,720,8,10,0,1
2,28,3.8,600,4,5,1,0
3,35,10.5,780,12,15,0,1
4,40,12.0,800,15,20,0,1
...,...,...,...,...,...,...,...
95,54,10.7,745,10,14,1,1
96,59,9.2,725,9,16,0,1
97,38,5.2,595,3,9,1,0
98,41,9.7,755,8,14,0,1
99,36,5.7,625,4,10,0,0

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [29]:
X=df[['Age',	'Annual_Income_Lakhs'	,'Credit_Score',	'Loan_Amount_Lakhs',	'Loan_Term_Years',	'Employee_Type']]
y=df['Loan_Approved']

In [30]:
X_train,X_test,y_train,y_test=train_test_split  (X,y,test_size=0.2,random_state=42)

In [31]:
standard=StandardScaler()
X_test=standard.fit_transform(X_test)
X_train=standard.fit_transform(X_train)

In [41]:
model=LogisticRegression(max_iter=2000)
model.fit(X_train,y_train)
model.predict([[55	,4.5,	450	,20,	20,0]])
y_pred = model.predict(X_test)
#print("Accuracy:", accuracy_score(y_test, y_pred))
#print(classification_report(y_test, y_pred))
print(y_pred)
df1=pd.concat([pd.DataFrame(X_test),pd.DataFrame(y_pred)],axis=1)
df1

[1 1 1 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 1]

           0         1         2         3         4    5  0
0   0.873558  1.538156  1.435671  1.334039  1.162182 -0.5  1
1   0.493750  1.259337  1.242097  1.334039  0.599836 -0.5  1
2  -0.519071 -0.413583 -0.306491 -0.698783 -0.899754 -0.5  1
3   1.633173  0.391897  0.145180  0.571731  0.412387  2.0  1
4   1.000160  1.631096  1.435671  1.842245  2.286875 -0.5  1
5  -0.772276 -1.250043 -1.467933 -1.206988 -0.524857 -0.5  0
6  -0.772276 -1.095143 -1.274359 -0.698783 -0.899754  2.0  0
7  -0.392468 -0.320643 -0.241967 -0.444680 -0.712305 -0.5  1
8  -1.278686 -0.971223 -0.693639 -0.698783 -1.087203 -0.5  0
9  -1.405288 -1.064163 -0.758163 -0.952885 -1.274652 -0.5  0
10 -0.392468 -0.196723  0.080656  0.063526 -0.149959 -0.5  1
11 -1.025481 -0.785343 -0.564590 -0.952885 -0.712305 -0.5  0
12  0.746955  1.445216  1.371146  1.079937  0.974734 -0.5  1
13  0.240545  1.073457  1.113048  0.825834  1.162182 -0.5  1
14 -0.265865 -0.227703 -0.177442 -0.952885 -0.524857 -0.5  1
15  0.493750  1.259337  1.177573  1.588142  1.537080 -0.5  1
16  2.645994  0.206017  0.080656  0.317628  0.412387 -0.5  1
17 -0.012660 -1.033183 -1.596982 -1.206988 -0.899754  2.0  0
18 -0.898878 -1.188083 -1.338884 -0.952885 -1.087203  2.0  0
19 -0.392468 -0.258683  0.338754 -0.190577  0.224939 -0.5  1