<a href="https://colab.research.google.com/github/trupti2021/FirstGIT/blob/main/NNCreditCardFraudulent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [7]:
from tensorflow.keras import layers
from tensorflow.keras import models
import pandas as pd

In [8]:
df=pd.read_csv("/content/drive/MyDrive/AutogluonDrop/fraud_sample.csv")

In [9]:
df

,Transaction_Amount,Transaction_Time,Merchant_Category,Customer_Age,Account_Balance,Transactions_Today,FRAUD
0,1872.34,14,Grocery,45,45231.12,3,0
1,4321.10,2,Online,29,12000.50,15,1
2,120.55,10,Fuel,52,78000.00,2,0
3,3050.75,1,Online,34,15000.00,12,1
4,89.99,18,Restaurant,41,64000.25,1,0
5,560.20,20,Grocery,38,72000.10,4,0
6,2750.00,3,Travel,30,18000.00,11,1
7,45.60,12,Fuel,55,82000.00,2,0
8,3999.99,23,Online,27,10000.00,14,1
9,150.00,9,Restaurant,48,50000.00,3,0
10,2200.45,4,Online,36,20000.00,8,1
11,75.25,16,Grocery,60,90000.00,2,0
12,4999.99,0,Travel,28,15000.00,16,1
13,310.80,11,Fuel,42,67000.00,3,0
14,2700.10,2,Online,33,14000.00,13,1
15,60.50,15,Restaurant,50,55000.00,2,0
16,1850.75,19,Grocery,46,48000.00,5,0
17,4200.00,3,Online,31,11000.00,17,1
18,95.00,13,Fuel,58,88000.00,1,0
19,2500.00,22,Travel,37,21000.00,9,1

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Merchant_Category']=le.fit_transform(df['Merchant_Category'])
df

,Transaction_Amount,Transaction_Time,Merchant_Category,Customer_Age,Account_Balance,Transactions_Today,FRAUD
0,1872.34,14,1,45,45231.12,3,0
1,4321.10,2,2,29,12000.50,15,1
2,120.55,10,0,52,78000.00,2,0
3,3050.75,1,2,34,15000.00,12,1
4,89.99,18,3,41,64000.25,1,0
5,560.20,20,1,38,72000.10,4,0
6,2750.00,3,4,30,18000.00,11,1
7,45.60,12,0,55,82000.00,2,0
8,3999.99,23,2,27,10000.00,14,1
9,150.00,9,3,48,50000.00,3,0
10,2200.45,4,2,36,20000.00,8,1
11,75.25,16,1,60,90000.00,2,0
12,4999.99,0,4,28,15000.00,16,1
13,310.80,11,0,42,67000.00,3,0
14,2700.10,2,2,33,14000.00,13,1
15,60.50,15,3,50,55000.00,2,0
16,1850.75,19,1,46,48000.00,5,0
17,4200.00,3,2,31,11000.00,17,1
18,95.00,13,0,58,88000.00,1,0
19,2500.00,22,4,37,21000.00,9,1

In [ ]:
import numpy as np
impo